### ISSUE TITLE
Drop Down with searchable entities

### ISSUE THREAD

**Issue by dmkjr** [dylandoamaral/uptime-card#170]
New to your project here.  Installed 0.15 and found when attempting to setup that I have a list of 1,000 entities.  

Would it be possible to put these into a searchable field similar to the automation process of selecting a device within HA?

I will look at creating a PR and implementing the change.  It appears this hasn't been updated in some time -- not sure if its current.

**Comment by dylandoamaral** [comment]
I am sorry, but I won't implement this feature because it is too specific. It is quite similar to https://github.com/dylandoamaral/uptime-card/issues/161, and I think the best way to implement it is to create a surcomponent that can provide this dropdown for any kind of card making it powerful and composable. I still maintain the package if there is annoying bugs.
